dist: trusty
sudo: required
addons:
    apt:
        packages:
            - mysql-server-5.6
            - mysql-client-core-5.6
            - mysql-client-5.6
language: php
php:
    - '5.6'
install:
    - composer install
    - cp .env.example .env
    - sed -i 's/^DB_USERNAME=.*$/DB_USERNAME=root/g' .env
    - sed -i 's/^DB_PASSWORD=.*$/DB_PASSWORD=/g' .env
    - sed -i 's/^DB_DATABASE=.*$/DB_DATABASE=testing_db/g' .env
    - mysqladmin create testing_db
    - php artisan key:generate
    - php artisan migrate -v
    - php artisan migrate:rollback -v
    - php artisan migrate -v
script: composer ci
